### PR TITLE
Add function to create a shift matrix

### PR DESCRIPTION
**Pull request by bantin**

### CODE REVIEW

**Review by degleris1 — CHANGES_REQUESTED** [review]
Could we use a shorter function, previously implemented in the `projected_als` branch. It is given by
```julia
function shift_matrix(T, l)
    return diagm(l => ones(T-abs(l)))
end
```

**Comment by ahwillia** [comment]
Why do we want to represent this matrix explicitly? Can't this be done with indexing operations ([as we did in cmfpy](https://github.com/degleris1/cmfpy/blob/master/cmfpy/common.py#L89))?

**Comment by bantin** [comment]
@ahwillia I think long-term we plan to try and avoid explicitly representing the shift matrices. For prototyping the ANNLS and Projected ALS algorithms though, it's helpful to be able to explicitly represent them.

**Comment by bantin** [comment]
@degleris1  Updated it to be the shorter shift matrix function from projected_als. Okay to merge?

**Pull request merged**
